### ISSUE TITLE
Query: tool fails when SQL query contains special characters

### ISSUE THREAD

**Issue by maximskorik** [RECETOX/galaxytools#144]
+ The tool will fail when run with a query containing special characters (e.g., `|`, `"`)
+ See the [Galaxy history](https://umsa.cerit-sc.cz/u/max/h/aplcms-ramclustr-data-conversion) for more details

This has to be fixed to use the tool as a step between apLCMS and RamClustR (#141)

**Comment by martenson** [comment]
The main reason why these queries fail is the default [Galaxy input sanitizer](https://docs.galaxyproject.org/en/master/dev/schema.html#tool-inputs-param-sanitizer) that will sanitize special characters like the ones you included. This is the sane thing to do and we have to reevaluate our approach if we need to stop sanitizing inputs since that is a pandora box of problems. 
The other reason is that you are using Oracle syntax (`||`) for concatenating and I doubt that is supported in pandasql.
I suspect the third reason is that you are trying to concatenate strings and numbers without casting/converting them but I'd have to look into what pandasql is doing to make sure.
