### ISSUE TITLE
query: fix tool versions to avoid failing always on first run due to having to pull the image

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#195]
https://github.com/RECETOX/galaxytools/blob/e4cdacabd9d58524d3271e005644b8f2d56d83fc/tools/query/query.xml#L19-L26

**Comment by martenson** [comment]
I don't think that will help. imho the tool needs to use `profile="16.04"` or `detect_errors` in order to ignore docker writing to stderr. The biocontainer this tool uses is not being updated with dependency version changes (https://biocontainers.pro/tools/mulled-v2-42d83023fd1a6129f494827a5a7bce49e8c39f84) and the reason for these images to not be available locally is probably our own storage management on compute nodes.

**Comment by martenson** [comment]
https://github.com/RECETOX/galaxytools/pull/247

**Comment by xtrojak** [comment]
I suppose the same thing needs to be adjusted also for `MSMetaEnhancer` (change `detect_errors` to `"aggressive"`).

**Comment by martenson** [comment]
@xtrojak I think [this](https://github.com/RECETOX/galaxytools/blob/master/tools/msmetaenhancer/msmetaenhancer.xml#L13) should be enough
