### ISSUE TITLE
Create tool which extracts CSV spectra from apLCMS output

### ISSUE THREAD

**Issue by hechth** [RECETOX/galaxytools#51]
apLCMS currently outputs an hdf file which contains the original R data. This output should be exported from the hdf to a CSV table with a specific format which fits RAMClustR.

Also see [here](https://github.com/RECETOX/apLCMS/issues/7) for initial communication about HDF

## Notes
HDF files can be read into pandas data frame and pandas dataframes can be written to csv via 
```python
# Read from HDF
pandas.read_hdf("path/to/file.h5", "name_of_the_table_or_internal_hdf_path")

# Write to csv
dataframe = pandas.DataFrame(data=scores.scores, index=reference_names, columns=query_names)
dataframe.to_csv(args.output_filename, sep=';')
```

## Subtasks
- [x] Make selectable which table from the output to export
- [ ] (Optional) Choose how to format the file (rows/cols etc.)

**Comment by xtracko** [comment]
The CSV format for RamClustR may not be suitable. I am not sure how imprecise our floating points will become when converting from IEEE 754 to decadic and then back to IEEE 754. The peaks have at least 10^-6 precision. I will investigate it on our data...

This tool will be certainly useful when we want to see the results at the end of the Galaxy Workflow (see issue #27). But I am a little bit sceptical on using CSV as a data exchange format between individual stages in our Galaxy Workflow.

**Comment by hechth** [comment]
> The CSV format for RamClustR may not be suitable. I am not sure how imprecise our floating points will become when converting from IEEE 754 to decadic and then back to IEEE 754. The peaks have at least 10^-6 precision. I will investigate it on our data...
> 
> This tool will be certainly useful when we want to see the results at the end of the Galaxy Workflow (see issue #27). But I am a little bit sceptical on using CSV as a data exchange format between individual stages in our Galaxy Workflow.

We could also use the R HDF tool to create an "in-memory" csv or we have to adapt RAMClustR to work with this input.

**Comment by xtracko** [comment]
So I've measured the loss of accuracy when converting to a CSV on a reasonably large sample output from apLCMS. I've got a mean error of 10^-8 and max error 10^-5 which is getting into the territory we want to be accurate. So I would not recommend CSV or other text formats for floating-point numbers exchange.

The IEEE 754 numbers (stored in the form `(-1)^s * m * 2^e`) don't completely map onto the decimal notation (for instance some of the IEEE 754 numbers have an infinite notation in the decimal form). More on that topic [here](https://en.wikibooks.org/wiki/A-level_Computing/AQA/Paper_2/Fundamentals_of_data_representation/Floating_point_errors#Absolute_errors) and [here](https://matthew-brett.github.io/teaching/floating_error.html) and also in many books.

That being said, storing the floating-point numbers in a scientific notation could help because scientific notation, ie. 3e20, maps almost directly into IEEE 754 standard. But this would require a special CSV parser. Some CSV parsers allow this functionality but it would mean that this needs to be handled in every tool separately which is prone to errors and misunderstandings.

**Comment by hechth** [comment]
> So I've measured the loss of accuracy when converting to a CSV on a reasonably large sample output from apLCMS. I've got a mean error of 10^-8 and max error 10^-5 which is getting into the territory we want to be accurate. So I would not recommend CSV or other text formats for floating-point numbers exchange.

Does HDF store the data as binary?

**Comment by xtracko** [comment]
>  Does HDF store the data as binary?

Yes, that's why I have chosen the HDF format. Recently, I'm having second thoughts on that choice (it's hard to work with, the support in R is not as big as I thought, etc) but the general principles will be the same regardless of the binary format. I am considering SQLite or Parquet alternatives. If we choose something other than HDF, the adoption on the tooling side should be just a minor change.

> Btw. this would have also been useful to know in advance since I mentioned the RAMCLustR CSV based version in the internal meeting on 19.11. in more detail.

I'm sorry, I must have been asleep... 😞  It is generally discouraged to store high precision numbers in text formats. Only now, I found experimentally the absolute error on our data to have some hard evidence to support this general claim.

What data columns does RAMClustR need? If it's just a subset of the output of apLCMS you can read only those columns of interest in the RAMClustR wrapper. If some additional modifications are required then it's the same situation as in the Retip wrapper. We could probably come with some tool that can perform any SQL-like query on the data stored in HDF to avoid having many specific "bridging" tools (something like [SQL to Tabular](https://toolshed.g2.bx.psu.edu/view/iuc/query_tabular/2e8f945f7285) tool).

**Comment by hechth** [comment]
> What data columns does RAMClustR need? If it's just a subset of the output of apLCMS you can read only those columns of interest in the RAMClustR wrapper. If some additional modifications are required then it's the same situation as in the Retip wrapper. We could probably come with some tool that can perform any SQL-like query on the data stored in HDF to avoid having many specific "bridging" tools (something like SQL to Tabular tool).

That sounds like a good idea and useful extension of this. The only problem is we have to change any library or R tool to not use file based input. But I overall agree, that having a general data structure which can be queried and having such a querying tool is useful.

**Comment by ljocha** [comment]
Hi, 

I initiated more general discussion in Teams (the "File formats" channel).

For this particular purpose, I'd stick with a simple solution. Let's make a trivial tool which takes h5 as input, internal h5 path to the dataset as an additional parameter (which might be left emtpy if there's is just one dataset in the h5 file expected), and produce a CVS with all rows and colums of the dataset.

**Comment by hechth** [comment]
> Hi,

I initiated more general discussion in Teams (the "File formats" channel).

For this particular purpose, I'd stick with a simple solution. Let's make a trivial tool which takes h5 as input, internal h5 path to the dataset as an additional parameter (which might be left emtpy if there's is just one dataset in the h5 file expected), and produce a CVS with all rows and colums of the dataset.

I agree, but this is also something which might be addressed on a global scale. Maybe we should discuss this in the next meeting if necessary, but I think it can be postponed since there won't be many new tools wrapped in the very near feature. Maybe we can achieve a wider alignment with different groups as well, at least that would make sense.

**Comment by maximskorik** [comment]
I guess we can close this one a move on to #72
